/*  LA BASE DE DATOS BDARTICULOS ESTA ESTRUCTURADA DE LA SIGUIENTE MANERA */


struct ARTI {
	short int ART ;
	char COD[50];
	char DESC[100];
	char FAB[50];
	short int STOCK ;
};

/*

1.  HACER UN PROGRAMA DE LECTURA
2.  MOSTRAR LOS ARTICULOS CUYO STOCK ES MENOR QUE 8
3.  DETERMINAR QUIEN ES EL PROVEEDOR QUE MAS ARTICULOS SUMINISTRA
4.  PERMITIR EL INGRESO DE UN #ART Y BUSCARLO
5.  INDEXAR EL ARCHIVO
6.  ORDENAR EL INDICE
7.  REPETIR EL PUNTO 4 CON UNA BUSQUEDA BINARIA INDEXADA.

*/

int main()
{
	FILE * FP ;
	
	printf("\n\n   FIN DEL PROGRAMA");
	return 0 ;
}
